Include code alerts in api responses
chrisyang365/github-auditor pull request #38
Opened 2022-01-31 19:41 UTC by nicomwong

### Testing
Tested organizations and repositories with fake code_alerts; both worked
Did not test with more than 1 organization

### Changes
Organizations response: add "code_alerts_exist" field
Repositories response:   add "code_alerts" field

2022-01-31 19:43 UTC, nicomwong commented on app/controllers/api/repos_controller.rb
> +      repos = @organization.repositories
only changed index action; don't know why git shows full file diff

2022-01-31 19:44 UTC, nicomwong commented on app/controllers/api/repos_controller.rb
> +    before_action :get_orgs, :check_org
only changed index action; don't know why git shows full file diff

2022-01-31 21:20 UTC, chrisyang365 commented on app/controllers/api/repos_controller.rb
> +        repo_json["code_alerts"] = repo.code_alerts
per your suggestion in Discord, change this to display boolean `code_alerts_exist` field just like you did for orgs

2022-01-31 21:21 UTC, chrisyang365 requested changes

2022-01-31 21:21 UTC, chrisyang365 commented on app/controllers/api/repos_controller.rb
> +        repo_json["code_alerts"] = repo.code_alerts
per your suggestion in Discord, change this to display boolean `code_alerts_exist` field just like you did for orgs

2022-02-05 03:09 UTC, chrisyang365 approved these changes

2022-02-05 03:09 UTC, merged